---
- name: update apt
  apt:
    name: "*"
    state: latest
- name: install packages to allow apt to use a repository over HTTPS
  apt:
    name: software-properties-common
    state: installed
- name: timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo