---
- name: apt update
  apt:
    name: "*"
    state: latest
- name: install latest apt-transport-http
  apt:
    name: apt-transport-https
    state: latest
- name: install latest ca-certificates
  apt:
    name: ca-certificates
    state: latest
- name: install latest curl
  apt:
    name: curl
    state: latest
- name: add docker gpg public key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: define lsb_release -cs
  shell: lsb_release -cs
  ignore_errors: true
  register: lsb_release
- name: add apt repository for docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    state: present
- name: apt update
  apt:
    name: "*"
    state: latest
- name: install docker-ce
  apt:
    name: docker-ce
    state: latest
